### ISSUE TITLE
Add a simplifier function

### ISSUE THREAD

**Issue by gallais** [frex-project/idris-frex#29]
At the moment we can prove two expressions to be equal but we don't
have a `simplify` tactic exposing the normaliser and giving you:
`t ~ norm t`.

The normal form may not always be ideal but I know that this is something
that is sometimes convenient in Coq (ring/field)_simplify.

**Comment by ohad** [comment]
Will be closed by this [PR](https://github.com/gallais/idris-frex/pull/3), followed by #27 and #30 .
